app:
  build: .
  working_dir: /app
  volumes:
    - .:/app
  command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0 -p 3000"
  ports:
    - "3000:3000"
  links:
    - db
db:
  image: postgres:latest
  volumes:
    - ./db/dumps:/app-db-dumps # We're mounting this folder so we can backup/restore database dumps from our app folder.
    - ./db/postgres-setup.sql:/docker-entrypoint-initdb.d/setup.sql
  ports:
    - "5432:5432"
  environment:
    DB_HOST: db
